Repository hkaur008/Hacktoberfest-21, pull requests merged in 2021-10, with the labels that each got.

#4 Create printing_Hello_world.cpp
  C++ codes/printing_Hello_world.cpp
Labels: enhancement, hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#13 readme updated
  README.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#9 📝 added MIT licence
  LICENCE.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#12 Create Contributors.md
  Contributors.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#14 Update README.md
  README.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#10 Create Leetcode 7. Reverse Integer
  C++ codes/Leetcode 7. Reverse Integer
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#16 Update LICENCE.md
  LICENCE.md
Labels: good first issue, hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#18 Update script.js
  script.js
Labels: good first issue, hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#26 navbar added
  HacktoberFestShortLogo.svg
  home.css
  index.html
  script.js
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#17 machine learning
  Contributors.md
  Machine_learning/heart-attack-analysis-and-prediction.ipynb
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#20 #5 gitignore file
  .gitignore
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#44 Update index.html
  index.html
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#42 Create Fibanacci.cpp
  C++ codes/Fibanacci.cpp
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#19 add .gitignore contirbution
  .gitignore
  Contributors.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#46 Added factorial snippet
  C++ codes/factorial.cpp
  Contributors.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#21 Linear Search Program
  C++ codes/linearSearch.cpp
  Contributors.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#23 adding my name Atif in Contributors.md
  Contributors.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#28 Added c++ programs
  C++ codes/coin.cpp
  C++ codes/long_inc_subseq.cpp
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#29 Pallavi's Profile Added
  script.js
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#30 Create Ali_and_helping_innocent_people.cpp
  C++ codes/Ali_and_helping_innocent_people.cpp
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#31 Update Contributors.md
  Contributors.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#35 Issueresolution
  index.html
  script.js
Labels: hactoberfest, hacktoberfest-21

#33 Added Profile Mayank
  script.js
Labels: hactoberfest, hacktoberfest-21

#36 C++ Celsius to Fahrenheit and added name in Contributors.md
  Contributors.md
  celsiusToFahrenheit.cpp
Labels: hactoberfest, hacktoberfest-21

#37 amanverma644 added some leetcode solutions
  C++ codes/LeetCode Solutions/1031. Maximum Sum of Two Non-Overlapping Subarrays.txt
  C++ codes/LeetCode Solutions/1143. Longest Common Subsequence.txt
  C++ codes/LeetCode Solutions/115. Distinct Subsequences.txt
  C++ codes/LeetCode Solutions/1493. Longest Subarray of 1's After Deleting One Element.txt
  C++ codes/LeetCode Solutions/15. 3SUM.txt
  C++ codes/LeetCode Solutions/1646. Get Maximum in Generated Array.txt
  C++ codes/LeetCode Solutions/198. House Robber.txt
  C++ codes/LeetCode Solutions/300. LIS.txt
  C++ codes/LeetCode Solutions/583. Delete Operation for Two Strings.txt
  C++ codes/LeetCode Solutions/62. Unique Paths.txt
  C++ codes/LeetCode Solutions/647. Palindromic Substrings.txt
  C++ codes/LeetCode Solutions/7. Reverse Integer
  C++ codes/LeetCode Solutions/712. Minimum ASCII Delete Sum for Two Strings.txt
  C++ codes/LeetCode Solutions/746. Min Cost Climbing Stairs.txt
  C++ codes/LeetCode Solutions/91. Decode Ways.txt
  C++ codes/Min Steps To One.txt
  Contributors.md
  index.html
  script.js
Labels: hactoberfest, hacktoberfest-21

#40 Added Majority Element problem
  C++ codes/Majority Element.cpp
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#41 Cyclic Sort
  C++ codes/CyclicSort.cpp
  C++ codes/CyclicSort.exe
  C++ codes/InsertionSort.cpp
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#45 Update index.html
  index.html
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#47 conflict resolved
  index.html
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#48 Swastik symbol made in Cpp
  C++ codes/Swastik.cpp
  Contributors.md
  maze.cpp
  script.js
Labels: hactoberfest, hacktoberfest-21

#49 Create PerfectNumber.cpp
  C++ codes/PerfectNumber.cpp
Labels: hactoberfest, hacktoberfest-21

#50 #8 Add a cool footer Footer updated
  home.css
  index.html
Labels: hactoberfest, hacktoberfest-21

#52 #3 Navbar
  home.css
  index.html
Labels: hactoberfest, hacktoberfest-21

#53 MachineLearning-IrisContribution
  Machine_learning/IRIS Dataset Classification using Different Approaches/README.md
  Machine_learning/IRIS Dataset Classification using Different Approaches/iris-implementation.ipynb
  Machine_learning/IRIS Dataset Classification using Different Approaches/iris_data.csv
Labels: hactoberfest, hacktoberfest-21

#54 lokesh21012002
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21

#55 Added armstrong program - Hacktoberfest-2021
  C++ codes/armstrong.cpp
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21

#61 Added some links(references) in README.md
  README.md
Labels: hactoberfest, hacktoberfest-21

#60 Made minute corrections in Contributors.md
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#58 Made the logo monochrome
  HacktoberfestLogo.svg
Labels: hactoberfest, hacktoberfest-21

#62 added my name in contributors.md
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21

#64 Ride and Transport Management System in C++
  C++ codes/rideTransportSystem/Project.cpp
  C++ codes/rideTransportSystem/Project.h
  C++ codes/rideTransportSystem/README.md
  C++ codes/rideTransportSystem/Source.cpp
  C++ codes/rideTransportSystem/TMS.png
Labels: hactoberfest, hacktoberfest-21

#65 LeetCode solution no 2025
  C++ codes/Codeforces/Codeforces Round #744 (Div. 3)/E1.PermutationMinimizationbyDeque.cpp
  C++ codes/LeetCode Solutions/2025. Maximum Number of Ways to Partition an Array.cpp
Labels: hactoberfest, hacktoberfest-21

#66 vishesh profile added
  C codes/LinkedList/allOperationsLL.c
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21

#68 Added a cpp linked list traversal file
  linked_list_traversal/Readme.md
  linked_list_traversal/linked_list_traversal.cpp
Labels: hactoberfest, hacktoberfest-21

#69 Create BinarySearch.cpp
  C++ codes/BinarySearch.cpp
  contributors.svg
  home.css
  index.html
Labels: hactoberfest, hacktoberfest-21

#67 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hactoberfest, hacktoberfest-21

#71 Update Contributors.md
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#72 Update script.js
  script.js
Labels: hactoberfest, hacktoberfest-21

#73 Update README.md
  README.md
Labels: hactoberfest, hacktoberfest-21

#74 Create SECURITY.md
  SECURITY.md
Labels: hactoberfest, hacktoberfest-21

#76 added solution of leetcode Q.201
  C++ codes/LeetCode Solutions/201. Bitwise AND of Numbers Range.txt
Labels: hactoberfest, hacktoberfest-21

#84 Q 204
  C++ codes/LeetCode Solutions/204.Count Primes
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21

#80 Added N-K Ladder Problem
  C++ codes/COUNT_BST.txt
  MAX_NON_ADJ_SUM.txt
  N-K LADDER.txt
Labels: hactoberfest, hacktoberfest-21

#81 Mehul Profile Update
  .vscode/settings.json
  script.js
Labels: hactoberfest, hacktoberfest-21

#86 Operations on Linked List
  C codes/LinkedList/allOperationsLL.c
  C++ codes/Codeforces/Codeforces Round #744 (Div. 3)/E1.PermutationMinimizationbyDeque.cpp
  C++ codes/CyclicSort.exe
  C++ codes/LeetCode Solutions/2025. Maximum Number of Ways to Partition an Array.cpp
  C++ codes/PerfectNumber.cpp
  C++ codes/Swastik.cpp
  C++ codes/armstrong.cpp
  C++ codes/rideTransportSystem/Project.cpp
  C++ codes/rideTransportSystem/Project.h
  C++ codes/rideTransportSystem/README.md
  C++ codes/rideTransportSystem/Source.cpp
  C++ codes/rideTransportSystem/TMS.png
  Contributors.md
  Machine_learning/IRIS Dataset Classification using Different Approaches/README.md
  Machine_learning/IRIS Dataset Classification using Different Approaches/iris-implementation.ipynb
  Machine_learning/IRIS Dataset Classification using Different Approaches/iris_data.csv
  README.md
  home.css
  index.html
  maze.cpp
  script.js
Labels: hactoberfest, hacktoberfest-21

#85 Update README.md
  README.md
Labels: hactoberfest, hacktoberfest-21

#87 Heap Sort
  C++ codes/HeapSort.h
Labels: hactoberfest, hacktoberfest-21

#88 Added Edit Distance problem
  C++ codes/Edit Distance.cpp
Labels: hactoberfest, hacktoberfest-21

#90 updated CPP question
  C++ codes/LeetCode Solutions/Find minimum and maximum element in an array.cpp
Labels: hactoberfest, hacktoberfest-21

#91 Add files via upload
  C++ codes/knapsack_memoreisation_DP.cpp
Labels: hactoberfest, hacktoberfest-21

#92 Add Bubble Sort
  C++ codes/bubbleSort.cpp
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#106 Data Structures and Algorithm Folder Created
  DSA/Kruskal'sMinSpanningTree.cpp
  DSA/Merge_Sort-Recursive.c
  DSA/Mergesort.cpp
  DSA/PrimsMinSpanningTree.cpp
  DSA/Quicksort.cpp
  DSA/Radixsort.cpp
  DSA/Readme.md
  DSA/kadane_algo.cpp
  DSA/linkedList.cpp
  DSA/queue_implementation.cpp
  DSA/selectionSort.cpp
  DSA/shellsort.cpp
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#108 Create dark.css
  assets/dark.css
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#109 Create index.html for dark theme
  assets/index.html
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#110 Create monochrome HacktoberfestLogo.svg for dark theme
  assets/HacktoberfestLogo.svg
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#111 Create HacktoberfestShortLogo.svg
  assets/HacktoberfestShortLogo.svg
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#79 Question 4
  Codeforces/codeforces_744_div_3/a.cpp
  Codeforces/codeforces_744_div_3/d.cpp
  Contributors.md
  script.js
Labels: hactoberfest, hacktoberfest-21

#121 Addition of Javascript
  JavaScript/History_of_JavaScript.md
Labels: hactoberfest, hacktoberfest-21, hacktoberfest-accepted

#115 Create Detect-loop-in-linked-list.cpp
  DSA/Detect-loop-in-linked-list.cpp
Labels: hactoberfest, hacktoberfest-21

#116 Update README.md
  README.md
Labels: hactoberfest, hacktoberfest-21

#120 Add 2 C++ codes
  C++ codes/find_prime_factors.cpp
  C++ codes/pallendrome.cpp
Labels: hactoberfest, hacktoberfest-21

#122 added 2 LL programs in CPP, Updated the contributor's list
  C++ codes/LinkedList/ReverseLinkedList.cpp
  C++ codes/LinkedList/ReverseLinkedListInGROUPS.cpp
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#123 Prannov
  Contributors.md
  Machine_learning/Decision_Trees_and_Random_Forests_With_Python.ipynb
Labels: hactoberfest, hacktoberfest-21

#125 Added Kadane's Algo Code in Java
  Contributors.md
  Java_Codes/largestSumContiguousSubarray.java
  script.js
Labels: hactoberfest, hacktoberfest-21

#126 Added QR Code in Footbar
  Contributors.md
  assets/qrcode.png
  home.css
  index.html
Labels: hactoberfest, hacktoberfest-21

#128 Prim's Algorithm
  C++ codes/Prim's Algorithm.h
Labels: hactoberfest, hacktoberfest-21

#146 new problem solution added in c++ codes
  C++ codes/circularPrime.cpp
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#145 add problem 199 from Leetcode
  C++ codes/LeetCode Solutions/199. Binary Tree Right Side View.txt
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#144 Selection Sort in c++
  C++ codes/selection sort.cpp
  C++ codes/selection sort.exe
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#143 insertion sort added
  DSA/insertionsort.c
Labels: hactoberfest, hacktoberfest-21

#142 Create eulerTotient.cpp
  DSA/eulerTotient.cpp
Labels: hactoberfest, hacktoberfest-21

#148 Create QABC Snackdown.CPP
  C++ codes/QABC Snackdown.CPP
Labels: hactoberfest, hacktoberfest-21

#140 Finding Magic Number using Bitwise Operators
  C++ codes/MagicNumber.cpp
Labels: hactoberfest, hacktoberfest-21

#139 added implementation of stack and queue
  STACK AND QUEUE/implementating_queue_using_array.cpp
  STACK AND QUEUE/implementating_queue_using_linked_list.cpp
  STACK AND QUEUE/implementating_stack_using_array.cpp
Labels: hactoberfest, hacktoberfest-21

#138 Add oops and linked list part
  C++ codes/Oops/class.cpp
  C++ codes/Oops/encapsulation.cpp
  C++ codes/Oops/polymorphism.cpp
  Contributors.md
  DSA/Linked list/circular_ll.cpp
  DSA/Linked list/deletion_and_add_a_number_in_ll.cpp
  DSA/Linked list/doubly_ll.cpp
  DSA/Linked list/reverse_ll.cpp
  script.js
Labels: hactoberfest, hacktoberfest-21

#136 Create Non Repeating_Numbers.cpp
  C++ codes/Non Repeating_Numbers.cpp
Labels: hactoberfest, hacktoberfest-21

#117 issue #99- reduced space between footer icons
  .vs/hackoctoberHargun/config/applicationhost.config
  .vs/slnx.sqlite
  C++ codes/Binary_Search.cpp
  C++ codes/MergeSort.cpp
  Contributors.md
  home.css
  index.html
Labels: hactoberfest, hacktoberfest-21

#119 Update Index.html issue#97
  index.html
Labels: hactoberfest, hacktoberfest-21

#127 Added Spiral Traversal of Matrix
  C++ codes/spiraltraversal.cpp
Labels: hactoberfest, hacktoberfest-21

#149 Naeema
  C++ codes/naeema-19_equinox_codechef.
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#147 Create Code.Cpp
  Code.Cpp
Labels: hactoberfest, hacktoberfest-21

#141 Update Contributors.md
  Contributors.md
Labels: hactoberfest, hacktoberfest-21

#133 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hactoberfest, hacktoberfest-21

#132 Fixed very minute errors in assets/index.html
  assets/index.html
Labels: hactoberfest, hacktoberfest-21

#131 Add TowerOfHanoi
  C++ codes/TowerOfHanoi.cpp
Labels: hactoberfest, hacktoberfest-21

#130 Added Minimum Array Jump Code
  C++ codes/MINIMUM_ARRAY_JUMP.txt
Labels: hactoberfest, hacktoberfest-21
